# Numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.

File automatically generated. See the documentation to update questions/answers/hints programmatically.

#### 1. Import the numpy package under the name `np` (★☆☆)

In [1]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [2]:
print(np.__version__)
print(np.show_config())

1.23.5
openblas64__info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
    runtime_library_dirs = ['/usr/local/lib']
blas_ilp64_opt_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
    runtime_library_dirs = ['/usr/local/lib']
openblas64__lapack_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None), ('HAVE_LAPACKE', None)]
    runtime_library_dirs = ['/usr/local/lib']
lapack_ilp64_opt_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS

#### 3. Create a null vector of size 10 (★☆☆)

In [4]:
a=np.zeros(10)
a

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 4. How to find the memory size of any array (★☆☆)

In [30]:
b=np.zeros((10,10))
print(b.size)
print(b.itemsize)
print(b.size*b.itemsize,"bytes")

100
8
800 bytes


#### 5. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [31]:
null = np.zeros(10)
null[4] = 1
print(null)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 6. Create a vector with values ranging from 10 to 49 (★☆☆)

In [32]:
a= np.arange(start=10,stop=50)
a

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### 7. Reverse a vector (first element becomes last) (★☆☆)

In [33]:
array1 = [1, 2, 3, 4, 5]
array2 = array1[::-1]
print(array2)

[5, 4, 3, 2, 1]


#### 8. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [7]:
x=np.arange(9)
x=x.reshape(3,3)
x

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 9. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [34]:
nonzero = np.nonzero([1,2,0,0,4,0])
print(nonzero)

(array([0, 1, 4]),)


#### 10. Create a 3x3 identity matrix (★☆☆)
Hint : identity & eye, try to use 'help' to learn how to use two functions of numpy

In [35]:
a= np.identity(3)
a

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [36]:
b=np.eye(3)
b

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 11. Create a 3x3x3 array with random values (★☆☆)
Hint : numpy.random.random

In [38]:
a=np.random.random((3,3,3))
a

array([[[0.7484262 , 0.41230281, 0.66137445],
        [0.00931666, 0.20355841, 0.72798025],
        [0.01576351, 0.76747798, 0.54533191]],

       [[0.36153495, 0.86759377, 0.80560244],
        [0.46539773, 0.55036507, 0.63436503],
        [0.98409443, 0.87698259, 0.75048834]],

       [[0.96084315, 0.97948025, 0.24673098],
        [0.97258206, 0.58711896, 0.38208319],
        [0.5994934 , 0.59631441, 0.74837369]]])

#### 12. Create a 10x10 array with random values and find the **min**imum and **max**imum values (★☆☆)

In [11]:
x=np.random.random((10,10))
print(x)
print(x.min(), x.max())

[[0.22366241 0.76289794 0.08271976 0.64030222 0.30026758 0.86879492
  0.32365967 0.29649816 0.06757985 0.30663812]
 [0.41598571 0.8136609  0.11811282 0.4558935  0.38356825 0.76692116
  0.73442805 0.19684478 0.92752043 0.35531686]
 [0.91656248 0.0855408  0.92673298 0.44769049 0.64383152 0.54428615
  0.44332032 0.30955922 0.3174699  0.99885479]
 [0.51428093 0.03437201 0.99216079 0.8537271  0.26121892 0.56939617
  0.61536142 0.24336736 0.55516508 0.17470929]
 [0.47089071 0.09915503 0.03807128 0.37626995 0.8170573  0.85368661
  0.86925536 0.35409145 0.13865934 0.66939726]
 [0.47890948 0.62783962 0.76192494 0.17703861 0.4362456  0.09805643
  0.89709358 0.25410761 0.6787143  0.34169374]
 [0.63698723 0.06409732 0.02715944 0.67046278 0.12542634 0.10073041
  0.56024953 0.99641153 0.30882293 0.9598185 ]
 [0.75816863 0.51670674 0.00241938 0.01974056 0.44856227 0.06693489
  0.67550604 0.89900651 0.956296   0.84617716]
 [0.88689988 0.53985218 0.252183   0.60118478 0.38355506 0.03436917
  0.09859928

#### 13. Create a random vector of size 30 and find the **mean** value (★☆☆)

In [39]:
array = np.random.random(30)
print(array.mean())

0.5204151833011339


#### 14. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [40]:
x= np.ones([5,5])
x[1:-1,1:-1]=0
print(x)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


#### 15. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [41]:
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1

False

#### 16. Create a 5x5 matrix with values 1,2,3,4 just below the **diag**onal (★☆☆)

In [13]:
x=np.diag(1+np.arange(4),k=-1) # k는 대각선 위 아래를 뜻함. 따라서 k=-1을 해야 대각선 밑에 1,2,3,4 표현 가능
x

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

#### 17. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [42]:
array = np.zeros(64)
array = array.astype('int32')
array = array.reshape((8,8))
array[1::2, ::2] = 1 # 1번 행부터 끝까지, 2행씩 띄워서 출력, 모든 열 2열씩 띄워서 출력
array[::2, 1::2] = 1 # 모든 행 2행씩 띄워서 출력, 1번 열부터 끝까지 2열 씩 띄워서 출력
print(array)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 18. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)
Hint : use 'numpy.unravel_index(value, (x, y, z))

In [43]:
print(np.unravel_index(99,(6,7,8)))

(1, 5, 3)


#### 19. Normalize a 5x5 random matrix (★☆☆)
Hint : $Z = \frac{X - \overline{X}}{S}$

In [44]:
Z = np.random.random((5,5))
Z = (Z - np.mean(Z))/ (np.std(Z))
print(Z)

[[ 0.69700803  0.37767361 -1.56451441  0.14016711 -1.46921999]
 [-0.19822261  0.25112523 -0.48084224  1.32009582  0.53373347]
 [ 1.1765061   1.52928387 -0.49627627 -1.70771937 -0.87380241]
 [-0.18584104 -1.25786597  0.87587634  1.198205    0.50206578]
 [ 0.6663299  -2.0251729  -0.23068543  0.21197763  1.01011474]]


#### 20. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)
Hint : modify the code below
```python
numpy.dtype([(value, numpy.ubyte), … , (value, numpy.ubyte)])
```

In [27]:
RGBA = np.dtype([("R", np.ubyte),
                 ("G", np.ubyte),
                 ("B", np.ubyte),
                 ("A", np.ubyte)])
RGBA

dtype([('R', 'u1'), ('G', 'u1'), ('B', 'u1'), ('A', 'u1')])

#### 21. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [45]:
A = np.random.rand(5,3)
B = np.random.rand(3,2)
result = np.matmul(A,B)
print(result)

[[1.3825903  1.10972718]
 [1.40631888 0.85146723]
 [1.56906849 1.14376324]
 [0.54771945 0.3776532 ]
 [0.77610273 0.31295448]]


#### 22. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [46]:
array1d= np.arange(1,10)
a= array1d[3<array1d]
b= a[a<8]
print(b)

[4 5 6 7]


#### 23. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [1]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1)) # 결과가 달라진 이유가 의문.

9
10


#### 24. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

Z<Z>Z is legal

In [7]:
Z=[1,2,3]
Z<Z>Z

False

#### 25. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [12]:
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)

<ipython-input-12-cd809174da5d>:1: RuntimeWarning: invalid value encountered in divide
  np.array(0) / np.array(0)
<ipython-input-12-cd809174da5d>:2: RuntimeWarning: divide by zero encountered in floor_divide
  np.array(0) // np.array(0)


array([-9.22337204e+18])

#### 26. How to find common values between two arrays? (★☆☆)
```python
Z1 = np.random.randint(0,10,10)
Z2 = np.random.randint(0,10,10)
```
Hint : use `numpy.random.randint(start, end, size)`

In [18]:
Z1 = np.random.randint(0,10,10)
Z2 = np.random.randint(0,10,10)
z3= np.intersect1d(Z1,Z2)
print(z3)

[1 4 7 8]


#### 27. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [19]:
np.sqrt(-1) == np.emath.sqrt(-1)

<ipython-input-19-16339fbc685e>:1: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(-1) == np.emath.sqrt(-1)


False

False.

```np.lib.scimath.sqrt(-1)```

1j

#### 28. How to get all the dates corresponding to the month of July 2016? (★★☆)
Hint : modify the code below
```python
Z = np.arange('start', 'end', dtype='datetime64[D]')
```

In [25]:
Z = np.arange('2016-07','2016-08',
              dtype='datetime64[D]')
Z

array(['2016-07-01', '2016-07-02', '2016-07-03', '2016-07-04',
       '2016-07-05', '2016-07-06', '2016-07-07', '2016-07-08',
       '2016-07-09', '2016-07-10', '2016-07-11', '2016-07-12',
       '2016-07-13', '2016-07-14', '2016-07-15', '2016-07-16',
       '2016-07-17', '2016-07-18', '2016-07-19', '2016-07-20',
       '2016-07-21', '2016-07-22', '2016-07-23', '2016-07-24',
       '2016-07-25', '2016-07-26', '2016-07-27', '2016-07-28',
       '2016-07-29', '2016-07-30', '2016-07-31'], dtype='datetime64[D]')

#### 29. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)
Hint : use `numpy.add`, `numpy.divide`,`numpy.negative`, `numpy.multiply` and parameter `out` of the funtions

In [21]:
A = np.ones(3)*1
B = np.ones(3)*2
((A+B)*(-A/2))

array([-1.5, -1.5, -1.5])

In [20]:
A = np.ones(3)*1
B = np.ones(3)*2
Answer = np.ones(3)
np.add(A,B,out=B)
np.divide(A,2,out=A)
np.negative(A,out=A)
np.multiply(A,B,out=Answer)
# (1+2)*(-0.5) = -1.5
Answer

array([-1.5, -1.5, -1.5])

#### 30. Extract the integer part of a random array of positive numbers using 2 different methods (★★☆)
Hint : `%`, `//`

In [30]:
A=np.random.random(10)*10//1
A

array([8., 6., 5., 1., 5., 9., 9., 0., 2., 0.])

In [31]:
B = np.random.random(10)*10
B = B - B%1
B

array([3., 5., 1., 4., 4., 2., 7., 4., 9., 0.])

#### 31. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [34]:
Z = np.random.randint(0,4,25).reshape(5,5)
print(Z)

[[2 1 2 3 0]
 [1 3 1 1 3]
 [0 2 0 1 1]
 [2 2 1 1 1]
 [0 1 3 1 0]]


#### 32. Create a random vector of size 10 and sort it (★★☆)

In [44]:
a=np.random.randint(1,10,10)
print(a)
b=np.sort(a)
print(b)

[8 2 7 6 2 2 5 1 8 9]
[1 2 2 2 5 6 7 8 8 9]


#### 33. Consider two random array A and B, check if they are equal (★★☆)
```python
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)
```
Hint : Use `numpy.array_equal()`

In [45]:
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)
np.array_equal(A,B)

False

#### 34. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)
Hint 1 : Note that cartesian coodinate **(x, y)** can be represented as  polar coordinates **(distance from origin to (x,y), angle from the x-axis)**

Hint 2 : Use `numpy.sqrt` and `numpy.arctan2`

In [65]:
A=np.random.random((10,2))
print(A)
X,Y = A[:,0], A[:,1]
R = np.sqrt(X**2+Y**2)
T = np.arctan2(Y,X)
print(R)
print(T)
array = np.array(R)
R = array.reshape(10,1)
array1 = np.array(T)
T = array1.reshape(10,1)
arr = np.concatenate([R, T], axis=1)
arr

[[0.1193748  0.44068576]
 [0.98634272 0.97921316]
 [0.94231299 0.88708653]
 [0.72228618 0.85806944]
 [0.14276136 0.27549284]
 [0.27566708 0.45828904]
 [0.10695109 0.57428393]
 [0.63231057 0.58873735]
 [0.52724151 0.1618516 ]
 [0.40617959 0.2438877 ]]
[0.45656793 1.38986704 1.29417011 1.12159729 0.31028553 0.53480949
 0.584158   0.86396084 0.55152475 0.47377534]
[1.30626057 0.78177093 0.75521903 0.8711071  1.09269219 1.02926464
 1.38667184 0.74972819 0.29784636 0.54074518]


array([[0.45656793, 1.30626057],
       [1.38986704, 0.78177093],
       [1.29417011, 0.75521903],
       [1.12159729, 0.8711071 ],
       [0.31028553, 1.09269219],
       [0.53480949, 1.02926464],
       [0.584158  , 1.38667184],
       [0.86396084, 0.74972819],
       [0.55152475, 0.29784636],
       [0.47377534, 0.54074518]])

#### 35. Create random vector Z of size 10 and replace the maximum value by 0 (★★☆)
Hint : We can see the index of maximum value using `Z.argmax()`

In [66]:
z = np.random.random(10)
print(max(z))
z[z.argmax()] = 0
print(max(z))

0.8243994139235026
0.8173232510653419


#### 36. How to find the closest value (to a given scalar v) in a vector Z? (★★☆)
```python
Z = np.arange(100)
v = np.random.uniform(0,100)
```
Hint : Coumpute the distances between the each elements of Z and the scalar v. After that, we can see the index of minimum value using `argmin()`.  

In [75]:
Z = np.arange(100)
v = np.random.uniform(0,100)
x=(Z-v)*(Z-v)
x=sqrt(x)
print(x.argmin())
print(v)
Z[x.argmin()]


78
77.62374712761687


78

#### 37. What is the equivalent of enumerate for numpy arrays? (★★☆)
Hint : Use `numpy.ndenumerate()`or `numpy.ndindex()`

Example of the output :
```python
Z = np.arange(9).reshape(3,3)
```
```python
# output
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
```

In [81]:
a = np.arange(9).reshape(3,3)
for index, x in np.ndenumerate(a):
  print(index, x)

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


#### 38. How to randomly place p elements in a 2D array? (★★☆)
Hint : modify the code below
```python
n = 'size of a 2D array'
p = 'the number of elements that you want to place'
Z = np.zeros((n,n))
np.put(Z, np.random.choice(range(n*n), p, replace = False),'value that you want to place')
print(Z)
```

In [91]:
n = 3
p = 2
Z = np.zeros((n,n))
np.put(Z, np.random.choice(range(n*n), p, replace = False),4)
print(Z)

[[0. 4. 0.]
 [0. 0. 4.]
 [0. 0. 0.]]


#### 39. How to sort an array below by the nth column? (★★☆)
```python
Z = np.random.randint(0,10,(3,3))
```

In [108]:
# column 1
Z = np.random.randint(0,10,(3,3))
print(Z)
print(Z[Z[:, 0].argsort()])

[[8 1 1]
 [1 8 3]
 [2 8 7]]
[[1 8 3]
 [2 8 7]
 [8 1 1]]


In [109]:
# column 2
print(Z)
print(Z[Z[:, 1].argsort()])

[[8 1 1]
 [1 8 3]
 [2 8 7]]
[[8 1 1]
 [1 8 3]
 [2 8 7]]


In [110]:
# column 3
print(Z)
print(Z[Z[:, 2].argsort()])

[[8 1 1]
 [1 8 3]
 [2 8 7]]
[[8 1 1]
 [1 8 3]
 [2 8 7]]
