과제: 1p-38p 필사 및 개념 정리

# Chapter 1. 파이썬 기반의 머신러닝과 생태계 이해

## 1-1. 머신러닝의 개념

### 머신러닝의 분류
- 지도학습: 분류, 회귀, 추천 시스템, 시각/음성 감지/인지, 텍스트 분석 NLP
- 비지도학습: 클러스터링, 차원 축소, 강화학습

## 1-2. 파이썬 머신러닝 생태계를 구성하는 주요 패키지

- 머신러닝 패키지: 사이킷런
- 행렬/선형대수/통계 패키지: 넘파이, 사이파이
- 데이터 핸들링: 판다스, 맷플롯립
- 시각화: 맷플롯립, 시본

## 1-3. 넘파이

NumpPy: Numerical Python
- 파이썬에서 선형 대수 기반의 프로그램을 쉽게 만들 수 있도록 지원하는 대표적 패키지
- 루프를 사용하지 않고 대량 데이터의 배열 연산 가능하게 함. 빠른 배열 연산 속도 보장
- 다양한 데이터 핸들링 기능 제공.

### 넘파이 ndarray 개요

넘파이 모듈 임포트
```import numpy as np```
as np를 추가해 약어로 모듈 표현
- 넘파이 기반 데이터 타입: ndarray
- ndarray를 이용해 넘파이에서 다차원 배열을 쉽게 생성하고 다양한 연산 수행 가능
- array() 함수: 파이썬의 리스트 같은 다양한 인자를 입력 받아 ndarray로 변환하는 기능. 생성된 ndarray 배열의 shape 변수는 ndarray의 크기, 행과 열의 수를 튜플 형태로 가지고 있으며 ndarray 배열의 차원까지 알 수 있음.
- ndarray.shape: ndarray의 차원과 크기를 튜플 형태로 나타냄
  - ex) [1,2,3]의 shape (3,), 1차원
  - ex) [[1,2,3]]의 shape (1,3), 2차원
- array 함수의 인자로는 파이썬의 리스트 객체가 주로 사용됨. 리스트 []는 1차원, 리스트의 리스트[[]]는 2차원 같은 형태로 배열의 차원 및 크기 쉽게 표현 가능

### ndarray의 데이터 타입

- ndarray 내의 데이터 값은 숫자, 문자열, 불 값 모두 가능
- 숫자형: int(8,16,32 bit), unsigned int(8,16,32 bit), float(16,32,64,128 bit), complex
- ndarray 내의 데이터 타입은 같은 데이터 타입만 가능. 하나의 ndarray 객체에 int와 float 이 함께 있을 수 없음.
- dtype: ndarray 내의 데이터 타입 확인 가능
- 다른 데이터 유형이 섞인 리스트를 ndarray로 변경하면 데이터 크기가 더 큰 데이터 타입으로 형 변환 일괄 적용.
- astype(): ndarray 내 데이터 값의 타입 변경. 인자로 원하는 타입을 문자열로 지정. 메모리를 절약해야 할 때 주로 이용됨.

### ndarray를 편리하게 생성하기 - arange, zeros, ones

- 주로 테스트용으로 데이터를 만들거나 대규모의 데이터를 일괄적으로 초기화해야 할 경우 사용
- arange(): 파이썬 표준 함수인 range()와 유사한 기능. array를 range()로 표현하는 것. 0부터 함수 인자 값 -1까지의 값을 순차적으로 ndarray의 데이터값으로 변환. default 함수 인자는 stop 값. stop 값 -1까지 ndarray 데이터 입력됨. start로 시작 값 설정 가능
- zeros(): 튜플 형태의 shape 값 입력하면 모든 값을 0으로 채운 ndarray 반환
- ones(): 튜플 형태의 shape 값 입력하면 모든 값을 1로 채운 ndarray 반환


### ndarray의 차원과 크기를 변경하는 reshape()
- reshape(): ndarray를 특정 차원 및 크기로 변환. 변환을 원하는 크기를 함수 인자로 부여. 지정된 사이즈로 변경이 불가능하면 오류 발생.
  - 인자로 -1 적용하는 경우: 원래 ndarray와 호환하는 새로운 shape로 변환해줌.
  - 여래 개의 넘파이 ndarray는 stack 이나 concat으로 결합할 때 각각의 ndarray의 형태를 통일해 유용하게 사용됨

### 넘파이의 ndarray의 데이터 세트 선택하기 - 인덱싱(indexing)
- 인덱싱: 넘파이에서 ndarray 내의 일부 데이터 세트나 특정 데이터 만을 선택할 수 있도록 하는 인덱싱
1. 특정 데이터만 추출: 원하는 위치의 인덱스 값 지정 시 해당 위치의 데이터 반환
2. 슬라이싱(slicing): 연속된 인덱스상의 ndarray 추출
3. 팬시 인덱싱(Fancy indexing): 일정한 인덱싱 집합을 리스트 또는 ndarray 형태로 지정해 해당 위치에 있는 데이터의 ndarray 반환
4. 불린 인덱싱(Boolean Indexing): 특정 조건에 해당하는 지 여부인 True, False 값 인덱싱 기반으로 True 에 해당하는 인덱스 위치에 있는 데이터의 ndarray 반환

### 행렬의 정렬 - sort()와 argsort()
- np.sort(): 원 행렬은 그대로 유지한 채 원 행렬의 정렬된 행렬 반환
- ndarray.sort(): 원 행렬 자체를 정렬한 형태로 변환하면 반환 값은 None
- np.sort[::-1]: 내림차순으로 정렬
- np.argsort(): 원본 행렬이 정렬되었을 때 기존 원본 행렬 원소에 대한 인덱스가 필요할 때 사용.정렬 행렬의 원본 행렬 인덱스를 ndarray 형으로 반환

### 선형대수 연산 - 행렬 내적과 전치 행렬 구하기
- 행렬 내적(행렬 곱): np.dot(), 왼쪽 행렬의 행과 오른쪽 행렬의 열의 원소들을 순차적으로 곱한 뒤 그 결과를 모두 더한 값. 왼쪽 행렬의 열 개수와 오른쪽 행렬의 행 개수가 동일해야 내적 연산 가능
- 전치 행렬: 원 행렬에서 행열 위치를 교환한 원소로 구성한 행렬. transpose()

## 코드

In [1]:
import numpy as np

In [2]:
array1=np.array([1,2,3])
print('array1 type:', type(array1))
print('array1 array 형태:', array1.shape)

array2=np.array([[1,2,3],
                 [2,3,4]])
print('array2 type:', type(array2))
print('array2 array 형태:', array2.shape)

array3=np.array([[1,2,3]])
print('array3 type:', type(array3))
print('array3 array 형태:', array3.shape)

array1 type: <class 'numpy.ndarray'>
array1 array 형태: (3,)
array2 type: <class 'numpy.ndarray'>
array2 array 형태: (2, 3)
array3 type: <class 'numpy.ndarray'>
array3 array 형태: (1, 3)


In [3]:
print('array1: {:0}차원, array2: {:1}차원, array3:{:2}차원'.format(array1.ndim,array2.ndim, array3.ndim))

array1: 1차원, array2: 2차원, array3: 2차원


In [5]:
list1=[1,2,3]
print(type(list1))
array1=np.array(list1)
print(type(array1))
print(array1, array1.dtype) # 책에는 output이 int32인데 왜 다른지 궁금.

<class 'list'>
<class 'numpy.ndarray'>
[1 2 3] int64


In [6]:
list2=[1,2,'test']
array2=np.array(list2)
print(array2,array2.dtype) # output U21과 책에서의 U11 차이?

list3=[1,2,3.0]
array3=np.array(list3)
print(array3, array3.dtype)

['1' '2' 'test'] <U21
[1. 2. 3.] float64


In [7]:
array_int=np.array([1,2,3])
array_float=array_int.astype('float64')
print(array_float, array_float.dtype)

array_int1=array_float.astype('int32')
print(array_int1, array_int1.dtype)

array_float1=np.array([1.1,2.1,3.1])
array_int2=array_float1.astype('int32')
print(array_int2, array_int2.dtype)

[1. 2. 3.] float64
[1 2 3] int32
[1 2 3] int32


In [8]:
sequence_array=np.arange(10)
print(sequence_array)
print(sequence_array.dtype, sequence_array.shape) # int 디폴트 값이 달라졌나?

[0 1 2 3 4 5 6 7 8 9]
int64 (10,)


In [9]:
zero_array=np.zeros((3,2), dtype='int32')
print(zero_array)
print(zero_array.dtype, zero_array.shape)

one_array=np.ones((3,2))
print(one_array)
print(one_array.dtype, one_array.shape)

[[0 0]
 [0 0]
 [0 0]]
int32 (3, 2)
[[1. 1.]
 [1. 1.]
 [1. 1.]]
float64 (3, 2)


In [10]:
array1=np.arange(10)
print('array1:\n', array1)

array2=array1.reshape(2,5)
print('array2:\n', array2)

array3=array1.reshape(5,2)
print('array3:\n', array3)

array1:
 [0 1 2 3 4 5 6 7 8 9]
array2:
 [[0 1 2 3 4]
 [5 6 7 8 9]]
array3:
 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [11]:
array1.reshape(4,3)

ValueError: ignored

In [13]:
array1=np.arange(10)
print(array1)
array2=array1.reshape(-1,5)
print('array2 shape:', array2.shape)
array3=array1.reshape(5,-1)
print('array3 shape:', array3.shape)

[0 1 2 3 4 5 6 7 8 9]
array2 shape: (2, 5)
array3 shape: (5, 2)


In [14]:
array1=np.arange(10)
array4=array1.reshape(-1,4)

ValueError: ignored

In [15]:
array1=np.arange(8)
array3d=array1.reshape((2,2,2))
print('array3d:\n', array3d.tolist())

# 3차원 ndarray를 2차원 ndarray로 변환
array5=array3d.reshape(-1,1)
print('array5:\n', array5.tolist())
print('array5 shape:', array5.shape)

# 1차원 ndarray를 2차원 ndarray로 변환
array6=array1.reshape(-1,1)
print('array6:\n', array6.tolist())
print('array6 shape:', array6.shape)

array3d:
 [[[0, 1], [2, 3]], [[4, 5], [6, 7]]]
array5:
 [[0], [1], [2], [3], [4], [5], [6], [7]]
array5 shape: (8, 1)
array6:
 [[0], [1], [2], [3], [4], [5], [6], [7]]
array6 shape: (8, 1)


In [16]:
# 1부터 9까지의 1차원 ndarray 생성
array1=np.arange(start=1, stop=10)
print('array1:', array1)
# index는 0부터 시작하므로 array1[2]는 3번째 index 위치의 데이터 값을 의미
value=array1[2]
print('value:', value)
print(type(value))

array1: [1 2 3 4 5 6 7 8 9]
value: 3
<class 'numpy.int64'>


In [17]:
print('맨 뒤의 값:', array1[-1], '맨 뒤에서 두 번째 값:', array1[-2])

맨 뒤의 값: 9 맨 뒤에서 두 번째 값: 8


In [18]:
array1[0]=9
array1[8]=0
print('array1:', array1)

array1: [9 2 3 4 5 6 7 8 0]


In [19]:
array1d=np.arange(start=1, stop=10)
array2d=array1d.reshape(3,3)
print(array2d)

print('(row=0, col=0) index 가리키는 값:', array2d[0,0])
print('(row=0, col=1) index 가리키는 값:', array2d[0,1])
print('(row=1, col=0) index 가리키는 값:', array2d[1,0])
print('(row=2, col=2) index 가리키는 값:', array2d[2,2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(row=0, col=0) index 가리키는 값: 1
(row=0, col=1) index 가리키는 값: 2
(row=1, col=0) index 가리키는 값: 4
(row=2, col=2) index 가리키는 값: 9


In [20]:
array1=np.arange(start=1, stop=10)
array3=array1[0:3]
print(array3)
print(type(array3))

[1 2 3]
<class 'numpy.ndarray'>


In [21]:
array1=np.arange(start=1, stop=10)
array4=array1[:3]
print(array4)

array5=array1[3:]
print(array5)

array6=array1[:]
print(array6)

[1 2 3]
[4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]


In [22]:
array1d=np.arange(start=1, stop=10)
array2d=array1d.reshape(3,3)
print('array2d:\n', array2d)

print('array2d[0:2,0:2]\n', array2d[0:2,0:2])
print('array2d[1:3,0:3]\n', array2d[1:3,0:3])
print('array2d[1:3,:]\n', array2d[1:3,:])
print('array2d[:,:]\n', array2d[:,:])
print('array2d[:2,1:]\n', array2d[:2,1:])
print('array2d[:2,0]\n', array2d[:2,0])

array2d:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
array2d[0:2,0:2]
 [[1 2]
 [4 5]]
array2d[1:3,0:3]
 [[4 5 6]
 [7 8 9]]
array2d[1:3,:]
 [[4 5 6]
 [7 8 9]]
array2d[:,:]
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
array2d[:2,1:]
 [[2 3]
 [5 6]]
array2d[:2,0]
 [1 4]


In [23]:
print(array2d[0])
print(array2d[1])
print('array2d[0] shape:', array2d[0].shape, 'array2d[1] shape:', array2d[1].shape)

[1 2 3]
[4 5 6]
array2d[0] shape: (3,) array2d[1] shape: (3,)


In [24]:
array1d=np.arange(start=1, stop=10)
array2d=array1d.reshape(3,3)

array3=array2d[[0,1],2]
print('array2d[[0,1],2]=>', array3.tolist())

array4=array2d[[0,1],0:2]
print('array2d[[0,1],0:2]=>', array4.tolist())

array5=array2d[[0,1]]
print('array2d[[0,1]]=>', array5.tolist())

array2d[[0,1],2]=> [3, 6]
array2d[[0,1],0:2]=> [[1, 2], [4, 5]]
array2d[[0,1]]=> [[1, 2, 3], [4, 5, 6]]


In [25]:
array1d=np.arange(start=1, stop=10)
# [] 안에 array1d > 5 Boolean indexing 을 적용
array3=array1d[array1d>5]
print('array1d>5 불린 인덱싱 결과 값:', array3)

array1d>5 불린 인덱싱 결과 값: [6 7 8 9]


In [26]:
array1d>5

array([False, False, False, False, False,  True,  True,  True,  True])

In [27]:
boolean_indexes=np.array([False, False,False,False,False, True, True, True, True])
array3=array1d[boolean_indexes]
print('불린 인덱스로 필터링 결과:', array3)

불린 인덱스로 필터링 결과: [6 7 8 9]


In [28]:
indexes=np.array([5,6,7,8])
array4=array1d[indexes]
print('일반 인덱스로 필터링 결과:', array4)

일반 인덱스로 필터링 결과: [6 7 8 9]


In [29]:
org_array=np.array([3,1,9,5])
print('원본 행렬:', org_array)
# np.sort()로 정렬
sort_array1=np.sort(org_array)
print('np.sort() 호출 후 반환된 정렬 행렬:', sort_array1)
print('np.sort() 호출 후 원본 행렬:', org_array)
# ndarray.sort()로 정렬
sort_array2=org_array.sort()
print('org_array.sort() 호출 후 반환된 행렬:', sort_array2)
print('org_array.sort() 호출 후 원본 행렬:', org_array)

원본 행렬: [3 1 9 5]
np.sort() 호출 후 반환된 정렬 행렬: [1 3 5 9]
np.sort() 호출 후 원본 행렬: [3 1 9 5]
org_array.sort() 호출 후 반환된 행렬: None
org_array.sort() 호출 후 원본 행렬: [1 3 5 9]


In [30]:
sort_array1_desc=np.sort(org_array)[::-1]
print('내림차순으로 정렬:', sort_array1_desc)

내림차순으로 정렬: [9 5 3 1]


In [31]:
array2d=np.array([[8,12],
                  [7,1]])

sort_array2d_axis0=np.sort(array2d,axis=0)
print('로우 방향으로 정렬:\n', sort_array2d_axis0)

sort_array2d_axis1=np.sort(array2d, axis=1)
print('칼럼 방향으로 정렬:\n', sort_array2d_axis1)

로우 방향으로 정렬:
 [[ 7  1]
 [ 8 12]]
칼럼 방향으로 정렬:
 [[ 8 12]
 [ 1  7]]


In [32]:
org_array=np.array([3,1,9,5])
sort_indices=np.argsort(org_array)
print(type(sort_indices))
print('행렬 정렬 시 원본 행렬의 인덱스:', sort_indices)

<class 'numpy.ndarray'>
행렬 정렬 시 원본 행렬의 인덱스: [1 0 3 2]


In [34]:
org_array=np.array([3,1,9,5])
sort_indices_desc=np.argsort(org_array)[::-1]
print('행렬 내림차순 정렬 시 원본 행렬의 인덱스:', sort_indices_desc)

행렬 내림차순 정렬 시 원본 행렬의 인덱스: [2 3 0 1]


In [35]:
import numpy as np

name_array=np.array(['John','Mike','Sarah','Kate','Samuel'])
score_array=np.array([78,95,84,98,88])

sort_indices_asc=np.argsort(score_array)
print('성적 오름차순 정렬 시 score_array의 인덱스:', sort_indices_asc)
print('성적 오름차순으로 name_array의 이름 출력:', name_array[sort_indices_asc])

성적 오름차순 정렬 시 score_array의 인덱스: [0 2 4 1 3]
성적 오름차순으로 name_array의 이름 출력: ['John' 'Sarah' 'Samuel' 'Mike' 'Kate']


In [36]:
A=np.array([[1,2,3],
            [4,5,6]])
B=np.array([[7,8],
            [9,10],
            [11,12]])
dot_product=np.dot(A,B)
print('행렬 내적 결과:\n', dot_product)

행렬 내적 결과:
 [[ 58  64]
 [139 154]]


In [37]:
A=np.array([[1,2],
            [3,4]])
transpose_mat=np.transpose(A)
print('A의 전치 행렬:\n', transpose_mat)

A의 전치 행렬:
 [[1 3]
 [2 4]]
